#![expect(
    clippy::indexing_slicing,
    reason = "test: asserts on fixture-controlled indices"
)]
//! Parity tests: the Rust idealized coder must reproduce the numpy/spikecoder
//! golden fixtures (`tests/fixtures/coder_golden.json`, regenerated by
//! `generate_golden.py`) to <=1e-12 on closed-form quantities, the named rover
//! constants to 5e-5, and sampled quantities by statistical convergence only.

use std::fs;

use cog_spike::coder::{constants as k, information as info, latency as lat, source};
use serde_json::Value;

fn golden() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/coder_golden.json"
    );
    let text = fs::read_to_string(path).expect("read coder_golden.json");
    serde_json::from_str(&text).expect("parse coder_golden.json")
}

fn f(v: &Value) -> f64 {
    v.as_f64().expect("json number")
}

fn arr(v: &Value) -> Vec<f64> {
    v.as_array().expect("json array").iter().map(f).collect()
}

fn mat(v: &Value) -> Vec<Vec<f64>> {
    v.as_array().expect("json matrix").iter().map(arr).collect()
}

#[track_caller]
fn close(a: f64, b: f64, tol: f64, what: &str) {
    let d = (a - b).abs();
    assert!(d <= tol, "{what}: |{a} - {b}| = {d:e} > {tol:e}");
}

#[test]
fn named_constants_match_paper_and_golden() {
    let g = golden();
    let c = &g["constants"];
    // Paper precision (5e-5).
    close(*k::H_MARGINAL, 1.7500, 5e-5, "H_MARGINAL paper");
    close(*k::H_RATE, 0.9782, 5e-5, "H_RATE paper");
    close(*k::MUTUAL_INFO, 0.7718, 5e-5, "MUTUAL_INFO paper");
    // Byte parity with the numpy validators (1e-12).
    close(
        *k::H_MARGINAL,
        f(&c["H_MARGINAL"]),
        1e-12,
        "H_MARGINAL golden",
    );
    close(*k::H_RATE, f(&c["H_RATE"]), 1e-12, "H_RATE golden");
    close(
        *k::MUTUAL_INFO,
        f(&c["MUTUAL_INFO"]),
        1e-12,
        "MUTUAL_INFO golden",
    );
    close(k::LN2, f(&c["LN2"]), 1e-12, "LN2");
    close(k::LAMBDA, f(&c["LAMBDA"]), 1e-12, "LAMBDA");
    close(k::TAU_RC, f(&c["TAU_RC"]), 1e-12, "TAU_RC");
    close(
        lat::alpha_of(k::LAMBDA, k::TAU_RC),
        f(&c["ALPHA"]),
        1e-12,
        "ALPHA = 1/ln2",
    );
}

#[test]
fn softmax_matches_golden() {
    let g = golden();
    let inputs = g["softmax_inputs"].as_array().expect("inputs");
    let outputs = g["softmax_outputs"].as_array().expect("outputs");
    for (zin, qout) in inputs.iter().zip(outputs) {
        let q_rust = info::softmax(&arr(zin));
        for (a, b) in q_rust.iter().zip(arr(qout)) {
            close(*a, b, 1e-12, "softmax element");
        }
    }
}

#[test]
fn momentum_chain_and_entropies_match_golden() {
    let g = golden();
    let p_rust = source::momentum_chain(&k::PI, k::S);
    for (rr, rg) in p_rust.iter().zip(mat(&g["P"])) {
        for (a, b) in rr.iter().zip(rg) {
            close(*a, b, 1e-12, "P element");
        }
    }
    for (row, cg) in p_rust.iter().zip(arr(&g["cond_entropies"])) {
        close(info::entropy_bits(row), cg, 1e-12, "conditional entropy");
    }
}

#[test]
fn information_measures_match_golden() {
    let g = golden();
    for item in g["info_pq"].as_array().expect("info_pq") {
        let p = arr(&item["p"]);
        let q = arr(&item["q"]);
        close(
            info::entropy_bits(&p),
            f(&item["entropy_p"]),
            1e-12,
            "entropy_p",
        );
        close(
            info::cross_entropy_bits(&p, &q),
            f(&item["cross_entropy"]),
            1e-12,
            "cross_entropy",
        );
        close(info::kl_bits(&p, &q), f(&item["kl"]), 1e-12, "kl");
    }

    let p = source::momentum_chain(&k::PI, k::S);
    let pi = k::PI.to_vec();
    let cer = &g["cross_entropy_rate"];
    close(
        info::cross_entropy_rate(&p, &pi, &p),
        f(&cer["perfect"]),
        1e-12,
        "cross-entropy rate (perfect q = P)",
    );
    let memoryless: Vec<Vec<f64>> = (0..pi.len()).map(|_| pi.clone()).collect();
    close(
        info::cross_entropy_rate(&p, &pi, &memoryless),
        f(&cer["memoryless"]),
        1e-12,
        "cross-entropy rate (memoryless q = pi)",
    );
    let wrong = source::momentum_chain(&k::PI, 0.4);
    close(
        info::cross_entropy_rate(&p, &pi, &wrong),
        f(&cer["wrong_s04"]),
        1e-12,
        "cross-entropy rate (wrong s = 0.4)",
    );
}

#[test]
fn latency_matches_golden_and_is_surprisal() {
    let g = golden();
    let l = &g["latency"];
    let qs = arr(&l["qs"]);
    let analytic = arr(&l["analytic"]);
    let drive = arr(&l["calibration_drive"]);
    let nengo = arr(&l["nengo_first_spike_of_drive"]);
    let roundtrip = arr(&l["q_for_drive_roundtrip"]);

    for (i, &q) in qs.iter().enumerate() {
        let a_rust = lat::analytic_latency_ideal(q, k::LAMBDA);
        close(a_rust, analytic[i], 1e-12, "analytic latency");
        let j = lat::calibration_drive(q, k::LAMBDA, k::TAU_RC, k::THETA);
        close(j, drive[i], 1e-9, "calibration drive");
        let t = lat::nengo_first_spike_time(j, k::TAU_RC);
        close(t, nengo[i], 1e-12, "nengo first spike of drive");
        close(
            lat::q_for_drive(j, k::LAMBDA, k::TAU_RC, k::THETA),
            roundtrip[i],
            1e-12,
            "q_for_drive roundtrip",
        );
        // The load-bearing identity: first-spike latency IS surprisal.
        close(t, a_rust, 1e-12, "latency == surprisal");
    }

    close(
        lat::q_max_for_ceiling(k::RHEOBASE_CEILING, k::LAMBDA, k::TAU_RC),
        f(&g["q_max_for_ceiling"]),
        1e-12,
        "q_max for ceiling",
    );
    close(
        lat::t_min_for_ceiling(k::RHEOBASE_CEILING, k::LAMBDA, k::TAU_RC),
        f(&g["t_min_for_ceiling"]),
        1e-12,
        "t_min for ceiling",
    );
}

#[test]
fn gradient_identity_is_the_delta_rule() {
    // d(-log2 q_j)/dW[m] == (q_m - 1[m=j]) / ln2, so dW = eta*(y - q) is SGD on
    // the surprisal -log2 q_j. Numerically verified to <=1e-6.
    let w = [0.3_f64, -0.7, 1.1, -0.2];
    let j = 2usize;
    let q = info::softmax(&w);
    let eps = 1e-6;
    for m in 0..w.len() {
        let mut wp = w;
        let mut wm = w;
        wp[m] += eps;
        wm[m] -= eps;
        let lp = -info::softmax(&wp)[j].log2();
        let lm = -info::softmax(&wm)[j].log2();
        let numeric = (lp - lm) / (2.0 * eps);
        let onehot = if m == j { 1.0 } else { 0.0 };
        let analytic = (q[m] - onehot) / k::LN2;
        close(numeric, analytic, 1e-6, "gradient identity");
    }
}

#[test]
fn sampled_stream_converges_to_pi() {
    // RNG is Rust's StdRng, not numpy's PCG64, so assert statistical convergence
    // (not exact stream equality), exactly as test_spikecoder.py does.
    let src = source::RoverSource::paper();
    let stream = src.sample(200_000);
    let n = stream.len() as f64;
    let mut counts = [0usize; 4];
    for &s in &stream {
        counts[s] += 1;
    }
    for (i, &c) in counts.iter().enumerate() {
        close(c as f64 / n, k::PI[i], 0.01, "empirical marginal ~ pi");
    }
}
