#![expect(
    clippy::indexing_slicing,
    reason = "test: asserts on fixture-controlled indices"
)]
//! Parity tests: the Rust event-camera port (`dvs.rs`) must reproduce the numpy oracle
//! (`tests/fixtures/dvs_golden.json`, regenerated by `generate_dvs_golden.py`) BYTE-EXACT
//! on the integer event/residual maps and totals, and to <=1e-9 on the float ratios and
//! the jitter-sweep correlation. The oracle is the e16 integer residual identity
//! `resid = raw AND NOT predicted` (proven exact for `J_ON` >> theta), so this validates
//! the Rust port of bar brightness, edge events, `np.roll` prediction, and residual logic.

use std::fs;

use cog_spike::dvs::{self, BAR_W as W, P_PIXELS as P};
use serde_json::Value;

fn golden() -> Value {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/tests/fixtures/dvs_golden.json"
    );
    let text = fs::read_to_string(path).expect("read dvs_golden.json");
    serde_json::from_str(&text).expect("parse dvs_golden.json")
}

fn movie(v: &Value) -> Vec<Vec<u8>> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|row| {
            row.as_array()
                .expect("row array")
                .iter()
                .map(|x| u8::try_from(x.as_u64().expect("u8 cell")).expect("0..=255"))
                .collect()
        })
        .collect()
}

fn ints(v: &Value) -> Vec<i64> {
    v.as_array()
        .expect("array")
        .iter()
        .map(|x| x.as_i64().expect("i64"))
        .collect()
}

fn pearson(x: &[f64], y: &[f64]) -> f64 {
    let n = x.len() as f64;
    let mx = x.iter().sum::<f64>() / n;
    let my = y.iter().sum::<f64>() / n;
    let cov: f64 = x.iter().zip(y).map(|(a, b)| (a - mx) * (b - my)).sum();
    let vx = x.iter().map(|a| (a - mx).powi(2)).sum::<f64>().sqrt();
    let vy = y.iter().map(|b| (b - my).powi(2)).sum::<f64>().sqrt();
    cov / (vx * vy)
}

#[test]
fn canonical_schedule_is_byte_exact() {
    let g = golden();

    // our schedule reproduces numpy's positions / velocities exactly
    let (positions, _novel, vel) = dvs::build_schedule();
    assert_eq!(positions, ints(&g["positions"]), "schedule positions");
    assert_eq!(vel, ints(&g["vel_true"]), "true velocity");
    let v_hat = dvs::estimate_velocity_lagging(&vel);
    assert_eq!(v_hat, ints(&g["v_hat"]), "one-frame-lag v_hat");

    // raw events
    let b = dvs::brightness(&positions, P, W);
    let (on_raw, off_raw) = dvs::events_from_brightness(&b);
    assert_eq!(on_raw, movie(&g["on_raw"]), "ON raw map");
    assert_eq!(off_raw, movie(&g["off_raw"]), "OFF raw map");

    // predictive residual (the integer identity)
    let (on_pred, off_pred) = dvs::predict_events(&on_raw, &off_raw, &v_hat);
    let on_resid = dvs::residual_map(&on_raw, &on_pred);
    let off_resid = dvs::residual_map(&off_raw, &off_pred);
    assert_eq!(on_resid, movie(&g["on_resid"]), "ON residual map");
    assert_eq!(off_resid, movie(&g["off_resid"]), "OFF residual map");

    let raw_total = dvs::total(&on_raw) + dvs::total(&off_raw);
    let resid_total = dvs::total(&on_resid) + dvs::total(&off_resid);
    assert_eq!(raw_total, g["raw_total"].as_u64().expect("raw_total"));
    assert_eq!(resid_total, g["resid_total"].as_u64().expect("resid_total"));

    let ratio = raw_total as f64 / resid_total.max(1) as f64;
    assert!(
        (ratio - g["compression_ratio"].as_f64().expect("compression")).abs() < 1e-9,
        "compression ratio {ratio}"
    );
    // the headline e16 numbers
    assert_eq!(raw_total, 98);
    assert_eq!(resid_total, 12);
}

#[test]
fn jitter_sweep_is_exact_and_tracks_predictability() {
    let g = golden();
    let sweep = g["sweep"].as_array().expect("sweep array");

    let mut preds = Vec::new();
    let mut ratios = Vec::new();
    for s in sweep {
        let positions = ints(&s["positions"]);
        // the sweep uses a fixed +V predictor (the redundancy itself decays)
        let v_hat = vec![dvs::V; positions.len()];
        let (_on_resid, _off_resid, stats) = dvs::compress(&positions, &v_hat, P, W);
        assert_eq!(
            stats.raw_total,
            s["raw"].as_u64().expect("raw"),
            "sweep raw"
        );
        assert_eq!(
            stats.resid_total,
            s["resid"].as_u64().expect("resid"),
            "sweep resid"
        );
        assert!((stats.ratio - s["ratio"].as_f64().expect("ratio")).abs() < 1e-9);
        assert!((stats.predictability - s["predictability"].as_f64().expect("pred")).abs() < 1e-9);
        preds.push(stats.predictability);
        ratios.push(stats.ratio);
    }

    let corr = pearson(&preds, &ratios);
    let golden_corr = g["corr_pred_ratio"].as_f64().expect("corr");
    assert!(
        (corr - golden_corr).abs() < 1e-9,
        "corr {corr} vs golden {golden_corr}"
    );
    // compression tracks predictability (the e16 headline r = +0.841)
    assert!(corr > 0.5, "positive correlation");
}
